### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by arthurlogilab** [cirrax/openstack-nagios-plugins#1]
A debian package would be nice to deploy these plugins. 

We're contemplating contributing the debian packaging.

**Comment by trefzer** [comment]
If you checkout the debian branch, there's everything there to build a Debian package.
Ubuntu should also work (but did not test that).

**Comment by arthurlogilab** [comment]
Great, have you thought about submitting it to debian ? or at least to the openstack debian team ? (could be hosted on zigo's gplhost debian sources)

lintian complains about a few things : 

* date seems to be wrong (Thu not Mon on latest changelog)
* missing copyright file

**Comment by arthurlogilab** [comment]
By the way, we're looking into packaging the python-nagiosplugin dependency too : https://bitbucket.org/flyingcircus/nagiosplugin/issue/10/debian-packaging

**Comment by trefzer** [comment]
python-nagiosplugin is already available in jessie.
the lintian complains are fixed.
